name: Deploy to Deno Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # OIDC認証に必要
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/deployctl@v1
        with:
          project: shikafujimoto-code19
          entrypoint: main.ts
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
